author extension
open-contracting-extensions/ocds_withheldInformation_extension pull request #1
Opened 2023-06-20 15:42 UTC by odscjen

2023-06-25 23:41 UTC, duncandewhurst requested changes

2023-06-25 23:41 UTC, duncandewhurst commented on codelists/+itemClassificationScheme.csv
> +eu-non-publication-justification,European Union non publication justification,The main reasons for not immediately publishing a notice within the context of public procurement according to the legisl
```suggestion
eu-non-publication-justification,European Union non-publication justification,The main reasons for not immediately publishing information required by eForms within the context of public procurement according to the legislation of the European Parliament.,https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/non-publication-justification,withheldInformationRationaleClassifications
```

2023-06-25 23:41 UTC, duncandewhurst commented on release-schema.json
> +      "description": "Details about withheld information.",
```suggestion
      "description": "Details of items of information whose publication is temporarily or permanently withheld.",
```

2023-06-25 23:41 UTC, duncandewhurst commented on release-schema.json
> +      "description": "Details of a withheld item of information.",
```suggestion
      "description": "An item of information whose publication is temporarily or permanently withheld.",
```

2023-06-25 23:41 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The name of the withheld data field.",
```suggestion
          "description": "The identifer of the field in which the withheld information would otherwise be published.",
```

2023-06-25 23:41 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The title of the withheld data field.",
```suggestion
          "description": "The name or title of the field in which the withheld information would otherwise be published.",
```

2023-06-25 23:41 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The rationale for withholding this information.",
```suggestion
          "description": "The rationale for withholding the information.",
```

2023-06-25 23:41 UTC, duncandewhurst commented on release-schema.json
> +          "description": "Classifications of the rationale for withholding this information.",
```suggestion
          "description": "Classifications of the rationale for withholding the information.",
```

2023-06-25 23:41 UTC, duncandewhurst commented on extension.json
> +    "en": "Adds an array of withheldInformationItem objects to describe data points that are embargoed or permanently withheld from publication."
```suggestion
    "en": "Adds a top-level field to describe items of information whose publication is temporarily or permanently withheld."
```

2023-06-25 23:41 UTC, duncandewhurst commented on extension.json
> +    "en": "Withheld Information"
```suggestion
    "en": "Withheld information"
```

2023-06-25 23:41 UTC, duncandewhurst commented on README.md
> +Adds an array of `withheldInformation` objects to describe data points that are embargoed or permanently withheld from publication.
I think that an embargo can be permanent so I'm not sure it's quite the right word.

```suggestion
Adds an array of `withheldInformationItem` objects to describe items of information whose publication is temporarily or permanently withheld.
```

2023-06-25 23:41 UTC, duncandewhurst commented on README.md
> +      "id": "cro-bot-law-18d27a53-0109-4f93-9231-6659d931bce0",
```suggestion
      "id": "cro-bor-law-18d27a53-0109-4f93-9231-6659d931bce0",
```

2023-06-25 23:41 UTC, duncandewhurst commented on README.md
> +      "rationale": "Information delayed publication because of ...",
May as well fix the grammar in the eForms example!

```suggestion
      "rationale": "Publication of this information is delayed because...",
```

2023-06-26 21:58 UTC, jpmckinney reviewed
I've documented the order for keywords here now: https://ocds-standard-development-handbook.readthedocs.io/en/latest/meta/schema_style_guide.html#json-schema-keyword-order

2023-06-26 21:58 UTC, jpmckinney commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BG-8 (Not Immediately Published)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eFor
```suggestion
In the European Union, this extension's fields correspond to [eForms BG-8 (Not Immediately Published)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eForms fields, see [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/en/).
```

2023-06-26 21:58 UTC, jpmckinney commented on release-schema.json
> +          "description": "The date the withheld information will be published.",
```suggestion
          "description": "The date on which the withheld information will be published.",
```

2023-06-26 21:58 UTC, jpmckinney commented on release-schema.json
> +        "rationaleClassification": {
```suggestion
        "rationaleClassifications": {
```

2023-06-26 21:58 UTC, jpmckinney commented on release-schema.json
> +        "rationale": {
Move `rationale` down to be adjacent to `rationaleClassifications`.

2023-06-26 21:58 UTC, jpmckinney commented on release-schema.json
> +          "description": "The identifer of the field in which the withheld information would otherwise be published.",
```suggestion
          "description": "The identifer of the field with which the withheld information would otherwise be published.",
```

2023-06-26 21:58 UTC, jpmckinney commented on release-schema.json
> +          "description": "The name or title of the field in which the withheld information would otherwise be published.",
```suggestion
          "description": "The name or title of the field with which the withheld information would otherwise be published.",
```

2023-06-27 16:20 UTC, jpmckinney approved these changes

2023-06-27 16:21 UTC, merged